# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7273663acbdb81035047b2291e2078cf84be2a9badaf514b865589239d93258962baf079c42e7c24ac5240cb17bc8fea568c10e132b4714ebe70c2a45164cf8c

test:
  secret_key_base: 95a34f8b100a4469d5413d16e93597490495877bd65f1beae7dce8b7000bde88bfc4bbdeacee208a723a6c44934a886ac2aa5ae723877d7240abfa96a902cf61

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
